import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useCallback, useState } from 'react';
import Header from '../components/Header/header';
import Footer from '../components/Footer/footer';
import Login from '../components/Login/Login';

export default function Home() {
  const [isLogined, setLogined] = useState(false);

  const getLogin = useCallback((option: boolean) => () => setLogined(option), [setLogined]);

  return (
    <div>
      <Header />
      <div className={styles.container}>
        <Head>
          <title>VPI</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-gray-400 p-5">Welcome to VPI</h1>
        <Login isLogined={isLogined} getLogin={getLogin} />
      </div>
      <Footer />
    </div>
  );
}
