export const squads = [
  { squadid: 1, locationX: 0, locationY: 0, size: 50, unitType: "Тяж Конница" },
  {
    squadid: 2,
    locationX: 0,
    locationY: 50,
    changeByX: 1,
    changeByY: 1,
    size: 100,
    unitType: "Лёг Конница",
  },
  {
    squadid: 3,
    locationX: 0,
    locationY: 100,
    changeByX: 11,
    changeByY: 2,
    size: 200,
    unitType: "Тяж Конница",
  },
  {
    squadid: 4,
    locationX: 0,
    locationY: 200,
    changeByX: 22,
    changeByY: 0,
    size: 500,
    unitType: "Лёг Конница",
  },
  {
    squadid: 5,
    locationX: 0,
    locationY: 300,
    changeByX: 2,
    changeByY: 1,
    size: 20,
    unitType: "Тяж Конница",
  },
];
