export const unitsData = [
  {
    name: "Конница",

    subRows: [
      {
        id: 1,
        name: "Тяж Конница",
        attack: 60,
        health: 600,
        morality: 50,
        size: 3,
        price: 32,
        attackHorseman: 1.5,
        attackSwordsman: 2,
        attackSpearman: 1.5,
        cavalryDefense: 1,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 2,
        name: "Лёг Конница",
        attack: 50,
        health: 400,
        morality: 30,
        size: 3,
        price: 24,
        attackHorseman: 1.5,
        attackSwordsman: 1.5,
        attackSpearman: 1.5,
        cavalryDefense: 1,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 3,
        name: "Конный Лучник",
        attack: 25,
        health: 400,
        morality: 25,
        size: 3,
        price: 20,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1,
        swordDefense: 1,
        spearDefense: 1,
      },
    ],
  },
  {
    name: "Пехота",

    subRows: [
      {
        id: 4,
        name: "Копейщик",
        attack: 40,
        health: 300,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1.5,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 2,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 5,
        name: "Мечник",
        attack: 40,
        health: 300,
        morality: 40,
        size: 2,
        price: 13,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1.5,
        cavalryDefense: 1,
        swordDefense: 1,
        spearDefense: 1.5,
      },
      {
        id: 6,
        name: "Лучник",
        attack: 20,
        health: 200,
        morality: 20,
        size: 2,
        price: 15,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 7,
        name: "Одичалый",
        attack: 25,
        health: 400,
        morality: 30,
        size: 2,
        price: 9,
        attackHorseman: 1.3,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1.7,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 8,
        name: "Вольные Кланы",
        attack: 50,
        health: 300,
        morality: 35,
        size: 2,
        price: 15,
        attackHorseman: 1,
        attackSwordsman: 1.4,
        attackSpearman: 1,
        cavalryDefense: 0.7,
        swordDefense: 0.7,
        spearDefense: 1,
      },
      {
        id: 9,
        name: "Ополченец",
        attack: 25,
        health: 250,
        morality: 25,
        size: 2,
        price: 4,
        attackHorseman: 1.1,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1.3,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 10,
        name: "Безупречный",
        attack: 45,
        health: 400,
        morality: 85,
        size: 2,
        price: 25,
        attackHorseman: 1.8,
        attackSwordsman: 1.5,
        attackSpearman: 1,
        cavalryDefense: 2,
        swordDefense: 1.5,
        spearDefense: 1,
      },
      {
        id: 11,
        name: "Спешенный рыцарь",
        attack: 60,
        health: 400,
        morality: 50,
        size: 2,
        price: 32,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1,
        swordDefense: 1.5,
        spearDefense: 1.5,
      },
      {
        id: 12,
        name: "Спешенный всадник",
        attack: 40,
        health: 300,
        morality: 40,
        size: 2,
        price: 24,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1.5,
        cavalryDefense: 1,
        swordDefense: 1,
        spearDefense: 1.5,
      },
      {
        id: 13,
        name: "Моряк",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 0.8,
        attackSwordsman: 1.4,
        attackSpearman: 1,
        cavalryDefense: 1,
        swordDefense: 1.4,
        spearDefense: 1,
      },
    ],
  },
  {
    name: "Флот",

    subRows: [
      {
        id: 14,
        name: "Пинас",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1.2,
        swordDefense: 1.5,
        spearDefense: 2,
      },
      {
        id: 15,
        name: "Ладья",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1,
        attackSwordsman: 1,
        attackSpearman: 1.5,
        cavalryDefense: 1,
        swordDefense: 1.2,
        spearDefense: 1.5,
      },
      {
        id: 16,
        name: "Драккар",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1.5,
        attackSwordsman: 1.2,
        attackSpearman: 1.1,
        cavalryDefense: 1,
        swordDefense: 1.1,
        spearDefense: 1.1,
      },
      {
        id: 17,
        name: "Баркалон",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1.5,
        attackSwordsman: 1,
        attackSpearman: 1,
        cavalryDefense: 1.2,
        swordDefense: 1,
        spearDefense: 1,
      },
      {
        id: 18,
        name: "Галера",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1,
        attackSwordsman: 1.2,
        attackSpearman: 1.5,
        cavalryDefense: 1,
        swordDefense: 1.2,
        spearDefense: 1,
      },
      {
        id: 19,
        name: "Галеон",
        attack: 35,
        health: 350,
        morality: 40,
        size: 2,
        price: 12,
        attackHorseman: 1,
        attackSwordsman: 2,
        attackSpearman: 1.2,
        cavalryDefense: 1,
        swordDefense: 1.2,
        spearDefense: 1.2,
      },
    ],
  },
];
