export const unitsDataTest = [
  {
    id: 1,
    name: "Тяж Конница",
    attack: 60,
    health: 600,
    morality: 50,
    size: 3,
    price: 32,
    attackHorseman: 1.5,
    attackSwordsman: 2,
    attackSpearman: 1.5,
    cavalryDefense: 1,
    swordDefense: 1,
    spearDefense: 1,
  },
  {
    id: 2,
    name: "Лёг Конница",
    attack: 50,
    health: 400,
    morality: 30,
    size: 3,
    price: 24,
    attackHorseman: 1.5,
    attackSwordsman: 1.5,
    attackSpearman: 1.5,
    cavalryDefense: 1,
    swordDefense: 1,
    spearDefense: 1,
  },
  {
    id: 3,
    name: "Конный Лучник",
    attack: 25,
    health: 400,
    morality: 25,
    size: 3,
    price: 20,
    attackHorseman: 1,
    attackSwordsman: 1,
    attackSpearman: 1,
    cavalryDefense: 1,
    swordDefense: 1,
    spearDefense: 1,
  },
];
